{% set name = "dmff" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/DMFF/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b38847ec0be34360c885f4c98dea93df1dc9ccd0e48dca84af5bac23f105ff26

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - numpy >=1.18
    - jax
    - jax-md >=0.2.4
    - mdtraj
    - optax >=0.1.4
    - pymbar >=4.0.0
    - openmm >=7.6.0
    - rdkit
    - freud
    - networkx >=3.0
    - tqdm
    - jaxopt >=0.8.0

test:
  imports:
    - dmff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmodeling/DMFF
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: DMFF (Differentiable Molecular Force Field) is a Jax-based python package that provides a full differentiable implementation of molecular force field models.
  doc_url: https://github.com/deepmodeling/DMFF
  dev_url: https://github.com/deepmodeling/DMFF

extra:
  recipe-maintainers:
    - njzjz
    - WangXinyan940
